# URL 列表，支持如下两种写法：
# urls:
#   - https://example.com
#   - https://httpbin.org/status/404
# 或：
# urls: [https://example.com, https://httpbin.org/status/404]
urls:
  - https://ai.dkk.qzz.io/v1
  - https://kkapi.cn.mt/v1
  - https://qqkk.us.ci/v1
  - https://ai.qqkk.cc.cd/v1
  

# 单个 URL 请求超时时间（毫秒）
timeout_ms: 10000

# 并发测试协程数
concurrency: 1
